### ISSUE TITLE
Tab center not disabled on nightly

### ISSUE THREAD

**Issue by JostCrow** [bwinton/TabCenter#1109] opened 2017-06-19 07:59 UTC
I know nightly is not supported but tab center does not work on nightly. I Thought reporting it will help that it will be supported in 6 weeks on beta. 

![screenshot from 2017-06-19 09-58-26](https://user-images.githubusercontent.com/390575/27275049-0a9d7b14-54d6-11e7-828c-4460dcc6e2e7.png)

**Comment by SoftVision-CiprianMuresan** [comment] 2017-06-19 08:10
Hi @JostCrow, thanks for the report. However it is a dupe of #1104. 
It might be supported in beta 56 but that depends on what will be uplifted from Nightly.
In the meantime you should consider trying out https://github.com/eoger/tabcenter-redux/ as this will be supported in Nightly 57.

**Closed by SoftVision-CiprianMuresan** 2017-06-19 08:10 UTC
