### ISSUE TITLE
Tab preview disappear while change tab order

### ISSUE THREAD

**Issue by bellayet** [bwinton/TabCenter#524] opened 2016-08-13 15:54 UTC
While I drag a tab to change the order. The preview of the web page at tab thumbnail disappear, never comes back again. 
![tab center tab preview](https://cloud.githubusercontent.com/assets/5299540/17644138/88874b06-61a0-11e6-8704-c35e92b0f66e.png)

**Comment by bwinton** [comment] 2016-08-13 16:45
Resolved duplicate of #511 (which will be fixed in the next release 🙂).  Thanks for the report!

**Closed by bwinton** 2016-08-13 16:45 UTC
