### ISSUE TITLE
[Enhancement] Option to move the entire UI to the right side of the browser

### ISSUE THREAD

**Issue by IsaacKhor** [bwinton/TabCenter#658] opened 2016-10-04 05:57 UTC
Instead of having the entire UI on the left side of the browser, why not have option to move the entire UI to the right side of the screen?

**Comment by bwinton** [comment] 2016-10-04 13:27
It's one of the oldest requests we have, but we haven't gotten around to it yet.

Resolving duplicate of #7.  :smile:

**Closed by bwinton** 2016-10-04 13:27 UTC
