### ISSUE TITLE
[Enhancement] Add close button to smaller views

### ISSUE THREAD

**Issue by ShalokShalom** [bwinton/TabCenter#974] opened 2017-03-01 10:24 UTC
![screenshot_20170301_112110](https://cloud.githubusercontent.com/assets/6344099/23455831/69823d1a-fe71-11e6-8ed5-edd157ece3aa.png)

I love this size and i think that a close button fits nice into that view, once the cursor move over the tab.

**Comment by SoftVision-CiprianMuresan** [comment] 2017-03-01 10:33
Hi again : ), thanks for the report. However this is a dupe of #836.

**Closed by SoftVision-CiprianMuresan** 2017-03-01 10:33 UTC
