### ISSUE TITLE
Search field is not persisting the filtering value when the sidebar is shrinked

### ISSUE THREAD

**Issue by kshetra03** [bwinton/TabCenter#913] opened 2017-01-31 09:34 UTC
Steps to re-create: 
- Firefox is opened with multiple tabs. 
- The left sidebar is shrinked. 
- Enter some filtering value in the search text field. 
- Remove the focus from the sidebar by hovering mouse on the browser window. 
- Mouse hover on the sidebar the expand and you will not find the filtering value that you have passed. 

What I observe is when the focus shifts away from the sidebar the filter is cleared to show all the opened tabs. 
If this is the case then with the sidebar opened, the filtering text persists even though the focus shifts away from the sidebar.

**Comment by SoftVision-CiprianMuresan** [comment] 2017-01-31 09:46
Hi @kshetra03, thanks for the report, however it is a dupe of #571.

**Closed by SoftVision-CiprianMuresan** 2017-01-31 09:46 UTC
