### ISSUE TITLE
Place navigation bar content in title bar

### ISSUE THREAD

**Issue by anonymous13587** [bwinton/TabCenter#949] opened 2017-02-21 22:29 UTC
In order to maximize vertical space available for displaying content, why not merge the navigation bar with the title bar? Unoccupied space could be draggable with some reserved next to the window controls like the current default tab bar behavior.

![capture2](https://cloud.githubusercontent.com/assets/25938118/23187674/abd83e94-f859-11e6-8c64-35595fe6643b.PNG)(this example uses [Vertical Tabs Reloaded](https://addons.mozilla.org/en-US/firefox/addon/vertical-tabs-reloaded/) for the tabs with [Classic Theme Restorer](https://addons.mozilla.org/en-US/firefox/addon/classicthemerestorer/) to merge the toolbars)

**Comment by SoftVision-CiprianMuresan** [comment] 2017-02-22 07:47
@anonymous13587, thanks for reporting this, however it is a dupe of #639.

**Closed by SoftVision-CiprianMuresan** 2017-02-22 07:47 UTC
