### ISSUE TITLE
Tabs are lost when clicking the "x more tabs..." option after performing a search

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [bwinton/TabCenter#733] opened 2016-10-27 15:03 UTC
[Affected versions]:
- Firefox 49.0.2 and up
- Tab Center 1.26.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to false and latest Tab Center add-on is installed.
- Have multiple tabs opened.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the Tab Center Sidebar search bar and enter a string that returns no results.
3. Click the "x more tabs..." option and observe the Sidebar behaviour.

[Expected result]:
- The search keyword is removed and all tabs are redisplayed.

[Actual result]:
- The search keyword is removed and all tabs are lost.

[Notes]:
- After this issue happens, the searched keywords do not return any results for newly opened tabs.
- This issue is not reproducible on the Tab Center version from Test Pilot.
- Added a screen recording with the issue: https://goo.gl/5tBWrS.

**Comment by ericawright** [comment] 2016-10-27 15:26
this was supposed to be fixed with #726. I'll look into it again, thank you!

**Closed** 2016-11-01 13:43 UTC

**Comment by SoftVision-CiprianMuresan** [comment] 2016-11-02 13:45
The issue is no longer reproducible on the latest Tab Center build (1.26.0 custom xpi).
