### ISSUE TITLE
Scroll position is lost after restarting the browser if a tab in the lower part of the Sidebar is focused

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [bwinton/TabCenter#738] opened 2016-10-28 13:33 UTC
[Affected versions]:
- Nightly 52.0a1
- Tab Center 1.26.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to false and latest Tab Center add-on is installed.
- "Show my windows and tabs from last time" option is enabled from about:preferences->General
- Have multiple tabs opened.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Hover the Tab Center Sidebar and scroll to the bottom of the list.
3. Focus one of the tabs from the bottom of the list.
4. Close and reopen/restart the browser with the same profile.
5. Observe the scroll position of the Sidebar.

[Expected result]:
- After the restart, the focused tab is in view in the Sidebar.

[Actual result]:
- After the restart, the scroll position is reset to the top of the Sidebar.

[Notes]:
- This issue is not reproducible on the Tab Center version from Test Pilot.
- Added a screen recording with the issue: https://goo.gl/g7QUVq.

**Comment by ericawright** [comment] 2016-11-14 14:47
this seems to be a duplicate of #693. Though I'm suspicious that it can't be duplicated on the released version

**Closed** 2016-11-15 19:16 UTC

**Comment by SoftVision-CiprianMuresan** [comment] 2016-11-16 09:55
The issue is no longer reproducible on the latest 1.26.0 build (custom xpi).
