### ISSUE TITLE
Does not play well with Tab Groups

### ISSUE THREAD

**Issue by forteller** [bwinton/TabCenter#499] opened 2016-08-08 08:30 UTC
When in a (smaller?) tab group you open a link in a new tab, all the tabs are shown in the sidebar until you switch tabs, at which time the view is changed back to only showing the tabs in the group you're currently in.

**Comment by brainsik** [comment] 2016-08-18 16:23
Unfortunately, this was reported a while ago in #453, but has since been lumped in with general "compatibility issues" in #464 with no promise of fixing.

The latest version has made things worse as it seems like every thumbnail is loaded when I start Firefox, which makes it unusable for a while. Seems like you have to pick Tab Center or Tab Groups here. :-(

**Comment by escapewindow** [comment] 2016-08-18 16:39
Yeah.  This is the issue that chased me back to Tree Style Tab.

**Comment by bwinton** [comment] 2016-08-18 16:43
Yeah.  I'm a big fan of Tab Groups, too, but we only have so much time to work on this add-on, and unfortunately getting it working with Tab Groups hasn't been the top-priority thing yet.  (And you're right, this is a dupe of #453/#464.

**Closed by bwinton** 2016-08-18 16:43 UTC
