### ISSUE TITLE
Alt text for "Sidebar open/close" button shows code

### ISSUE THREAD

**Issue by roldpescuela** [bwinton/TabCenter#961] opened 2017-02-24 21:38 UTC
It's pretty a minor error but can't help it. When I hover my cursor to the button to close or open the sidebar the alt text shows a code. That's all.

**Comment by SoftVision-CiprianMuresan** [comment] 2017-02-25 09:16
Hi @roldpescuela, thanks for reporting this, however it is a duplicate of #866.

**Closed by SoftVision-CiprianMuresan** 2017-02-25 09:16 UTC
