### ISSUE TITLE
New UI scrolling seems a little off

### ISSUE THREAD

**Issue by TDA** [bwinton/TabCenter#545] opened 2016-08-19 21:06 UTC
Scrolling seems to have more friction/jerkiness towards the end of the scroll in the new UI.

Screen:
![scroll](https://cloud.githubusercontent.com/assets/432707/17824321/0fbd513c-6616-11e6-969e-427f19ae1784.gif)

Screen doesnt seem to do justice, not sure of better way to show this

**Comment by chris-morgan** [comment] 2016-08-20 00:49
Looks like a duplicate of #273, which seems to me to be getting progressively worse.

**Comment by ericawright** [comment] 2016-09-08 16:48
@TDA can you describe a little more specifically what is "off" about them? Also, can you check out the newest version from master in nightly and tell me if it still seems jerky?

**Comment by TDA** [comment] 2016-09-08 18:59
@ericawright Tested on nightly, and this seems to occur when I have plenty of tabs(50+) open, the scrolling is jerky towards the beginning and end, kind of like this:
 http://cubic-bezier.com/#.33,.67,.93,.99
`bezier curve vs ease`

Only, with more friction towards the end and beginning, resulting in some movement against the direction I am scrolling in. Do you get what I am saying?

**Closed** 2017-05-16 20:01 UTC
Labels: ready
