### ISSUE TITLE
Wrong tab is focused when opening Firefox with Tab Center from external link

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [bwinton/TabCenter#847] opened 2016-12-14 15:12 UTC
[Affected versions]:
- Firefox 50.1.0 and above
- Tab Center 1.29.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Tab Center add-on is installed on a new clean profile.
- Have multiple tabs opened.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Focus one of the available tabs (except the first one) and after close the browser
3. Reopen it from the browser shortcut and observe the focused tab.
4. Focus another tab (except the first one) and close again the browser.
5. Choose to open the browser from an external link.
6. Observe the focused tab.

[Expected result]:
- Step 3: The same selected tab is focused when reopening the browser from its shortcut.
- Step 6: The same selected tab is focused when reopening the browser from an external link.

[Actual result]:
- Step 3: The same selected tab is focused when reopening the browser from its shortcut.
- Step 6: First opened tab is focused instead of the previously selected one when opening the browser from an external link.

[Notes]:
- This issue is reproducible with "reverse Tab Order" option set and the same first tab is focused.
- When there is at least one pinned tab in list, indifferent of the tabs ordering option, the first pinned tab is focused when opening the browser from external link.
- Here is a screen recording of the issue: https://goo.gl/3Z9TOq.

**Comment by Keith94** [comment] 2016-12-30 04:18
Dupe of #657?

**Closed** 2016-12-30 19:59 UTC
