### ISSUE TITLE
TabCenter Jumping to Top Scroll Tab List

### ISSUE THREAD

**Issue by ksec** [bwinton/TabCenter#693] opened 2016-10-12 13:57 UTC
On an opened 190 Tabs, from time to time Tab Center will Jump to the back to the Highest scroll list. ( Restarting Seems to solve it )

**Comment by ericawright** [comment] 2016-10-12 18:13
@ksec is this entirely fixed on restart? or is it still replicate-able? and if so, could you provide a gif?

**Comment by nth10sd** [comment] 2016-10-18 04:21
I think I hit this by:

* Force quit a Firefox instance with ~400 tabs
* Re-open Firefox with all the tabs, wait for it to load fully
* Scroll to the bottom-most tab, then read the webpage (scroll down or something)
* Tab Center jumps back to the highest scroll list.

After restarting, the tab center would jump back to the currently selected tab.

**Comment by ksec** [comment] 2016-10-18 04:35
Sorry My bad. I forgot to come back to this. Yes, everytime Firefox
unexpectedly quit or you restore a large number of tabs, this behaviour
appears.

**Comment by dannyhajj** [comment] 2016-10-21 12:16
Thought I'd let you know that I am not able to reproduce this issue on Ubuntu.
I Currently have 270 opened tabs on Firefox 50.0b3 & Ubuntu 16.04.1.
I tested this by killing Firefox with `pkill firefox`.

**Comment by ericawright** [comment] 2016-11-01 15:21
I've been able to duplicate:
![nov-01-2016 11-20-14](https://cloud.githubusercontent.com/assets/10803178/19894862/fb2c39d8-a024-11e6-92f7-e00d13db5f0c.gif)

- tabs on top pref is true (can replicate with false as well)
- open tabs from last time pref is true
- ~300 tabs

**Comment by tbs** [comment] 2016-11-13 18:55
Please, please and pleaaaaaaaaaaaaaaaaaaaaaaaaaaaase fix bugs more often!!!! For example, this bug (and many more) is present in extension half of 1 year already...... it is killing my browsing experience :\

**Closed** 2016-11-15 19:16 UTC
