### ISSUE TITLE
First window cannot interact with bookmark menu

### ISSUE THREAD

**Issue by brennie** [bwinton/TabCenter#715] opened 2016-10-19 23:44 UTC
When I start up a fresh browser window with TabCenter enabled, I am unable to interact with the bookmarks on the bookmark bar. It seems to cause [this bug](https://support.mozilla.org/en-US/questions/1031580).

STR:

1. Install Test Pilot + Tab Center
2. Add the Bookmarks bar
3. Restart Firefox
4. Right click on an entry in the bookmarks bar.

The right click menu on any bookmark/folder in the bookmarks bar will have all entries disabled (with the exception of _Open all Bookmarks_ for folders). (A screenshot is attached below.)

Opening a fresh window (as in the related bug I link) does seem to alleviate the problem, but only for the new window.

This happens on release (non-e10s), developer edition (e10s), and nightly (e10s) with a fresh profile and no other add-ons. (Even with test pilot disabled.)

![Right click menu](https://cloud.githubusercontent.com/assets/156585/19541420/5c0ae760-9623-11e6-80d4-2f774fb70c9a.png)

**Comment by ericawright** [comment] 2016-10-20 14:09
Thank you, this is a dupe of #583.
Also, thank you for the thorough info -- I did not realize that it only happens in the first window!

**Closed by ericawright** 2016-10-20 14:09 UTC
