### ISSUE TITLE
tab drag to diferent window broken

### ISSUE THREAD

**Issue by bakatom** [bwinton/TabCenter#346] opened 2016-06-07 13:57 UTC
Multiple times, I have tried to drag a tab from one window to another and had Firefox lock up.

- A new window [B] has a single tab [C].
- I click the tab and drag it to another existing window [A].
- The existing window [A] creates a new tab that is a blank "new tab" instead of moving the tab [C] I wanted moved.
- Firefox stops responding. Cannot submit feedback, cannot access "Addons" configuration.

I was able to reproduce this today in relation to another issue. When in my gmail web interface, I go to open Calendars from the gmail menu. Instead of opening in a new tab on the current window [A], it creates a new window [B] with the calendar in the new window. When attempting to move the calendar to window [A], it does not move the tab, it creates a new blank tab in window [A], and Firefox stops responding.

This was not the behavior before testing out this VerticalTabs addon, (which is awesome, btw). I don't know if I should submit another issue about some links, such as Calendars, opening in a new window instead of a new tab in the current window. 

I am going to try exiting out of Firefox nicely again, to see if it repeats again.

**Comment by bakatom** [comment] 2016-06-07 14:04
After testing it out by clean exit of Firefox, I am not able to reproduce it again at this time. It has happened very infrequently, maybe it is just an odd cache-related issue that is resolved by exiting Firefox.

**Comment by ericawright** [comment] 2016-06-07 19:25
I'm unable to reproduce either of those issues at the moment. Can you let me know which version of Firefox you are using, as well as your OS?

**Comment by bakatom** [comment] 2016-06-07 20:23
- Windows 10 Enterprise
 - Mozilla Firefox 46.0.1 (46.0.1.5966)

Have not yet updated to Firefox 47 that I just realized was released today.
It only happens randomly for me, I cannot reproduce it every time, and even
now I haven't had any problems since I cleanly exited and restarted Firefox
earlier today.

**Comment by bwinton** [comment] 2016-08-22 18:21
I just tried this, and it seems to be working now, so I'm going to close this bug, but please feel free to re-open it if you still see the problem.  Thanks!

**Closed by bwinton** 2016-08-22 18:21 UTC
