### ISSUE TITLE
Right Click Bookmarks Grayed Out

### ISSUE THREAD

**Issue by grimofdoom** [bwinton/TabCenter#706] opened 2016-10-17 00:07 UTC
When I use Tab Center, it grays out all options when I right click on my bookmarks bar. I tested to make sure it was Tab Center by disabling every add-on (which on Firefox restart, nothing was grayed out when right clicked). But then when I enable JUST Tab Center, all the options when I right click on bookmarks get grayed out.

**Comment by terrycloth** [comment] 2016-10-17 02:17
Looks like a duplicate of issue #704

**Comment by terrycloth** [comment] 2016-10-17 02:25
Actually, there's a lot of duplicates of this issue. I think the oldest one still open is #583.

**Comment by SoftVision-CiprianMuresan** [comment] 2016-10-17 10:17
@grimofdoom, thank you for reporting this, however it is a duplicate of #583.

**Closed by SoftVision-CiprianMuresan** 2016-10-17 10:17 UTC
