### ISSUE TITLE
Tabs changing height while closing tabs is confusing and can cause errors

### ISSUE THREAD

**Issue by mlissner** [bwinton/TabCenter#533] opened 2016-08-16 16:08 UTC
If you have a lot of tabs open, and you start closing them with the mouse, it's pretty smooth. You click the X, the next tab slides into place, and you can click its X without moving your mouse. This is feature parity with the traditional tabs.

BUT, with the regular tabs, they don't change size/shape until you move your mouse off the tabs, at which point they get wider. Otherwise, they stay the same (smaller) size as you're closing tabs, allowing you to just keep pressing the red X as it slides under your mouse.

[extraneous commentary that just serves to make developers sad deleted.]

**Comment by bwinton** [comment] 2016-08-16 16:15
Resolved duplicate of #465.

**Closed by bwinton** 2016-08-16 16:15 UTC

**Comment by mlissner** [comment] 2016-08-16 16:17
Yep. Apologies. I even looked for that yesterday, but missed it. My bad.
