### ISSUE TITLE
Bookmarks sidebar status (hidden/visible) is not remembered between sessions

### ISSUE THREAD

**Issue by noelj62** [bwinton/TabCenter#650] opened 2016-10-03 01:20 UTC
It seems that the bookmarks sidebar does not keep its status from session to a new session.
Here is the list of my installed and enabled addons:
![installed_and_enabled_addons](https://cloud.githubusercontent.com/assets/22582186/19025375/a47a0112-8920-11e6-93ec-1c0a209aff83.PNG)

**Comment by ericawright** [comment] 2016-10-21 17:06
I was not able to reproduce, even with all the same add-ons installed. Can you let me know what OS you're on and any other possible steps to reproduce?

**Comment by Keith94** [comment] 2016-12-30 04:17
This should be fixed in the latest version.

**Closed** 2017-01-01 10:19 UTC
