### ISSUE TITLE
Bookmarks of the personal bar are disabled

### ISSUE THREAD

**Issue by mentalo-** [bwinton/TabCenter#800] opened 2016-11-18 08:35 UTC
Hi there,

When Tab Center is enabled, i can't edit my bookmarks displayed in the personal bar of Firefox (menus are grey and unclickable). Please see here : 
https://framapic.org/icNcU1DowcqJ/xSzKh6LuaGCk.png

I have not incompatible extension installed (of this list https://github.com/bwinton/TabCenter#readme).

I often use the personal bar to manage quickly temporary bookmarks, so this behavior is embarrassing, i have to go in the bookmarks window each time.

I use Firefox 49.0.2 on Ubuntu Trusty, TabCenter 1.26 (all is up-to-date)

**Comment by SoftVision-CiprianMuresan** [comment] 2016-11-18 13:32
@mentalo-, thank you for reporting this, however it is a duplicate of #583.

**Closed by SoftVision-CiprianMuresan** 2016-11-18 13:32 UTC
