### ISSUE TITLE
Tab centre disables right click menu on Bookmarks bar

### ISSUE THREAD

**Issue by LarnuUK** [bwinton/TabCenter#710] opened 2016-10-19 08:41 UTC
When I enable the Tab Centre, all right click options for bookmarks on the bookmarks bar become disabled.

Disabling the Tab Centre does not resolve this, only a disable and close of Firefox fixes the problem. Enabling Tab Centre causes the issue immediately again.
![disabled bookmark](https://cloud.githubusercontent.com/assets/20837086/19511645/f9283c80-95df-11e6-86e2-af478ac86da1.png)

Bookmarks in the Menu Bar at the top function normally.

**Comment by SoftVision-CiprianMuresan** [comment] 2016-10-19 09:54
@LarnuUK, thank you for reporting this, however it is a duplicate of #583.

**Closed by SoftVision-CiprianMuresan** 2016-10-19 09:54 UTC
