### ISSUE TITLE
Group tabs per parent

### ISSUE THREAD

**Issue by k4ch0** [bwinton/TabCenter#1113] opened 2017-07-26 20:22 UTC
Hi!!!

It should be awesome if it is possible to group the tabs per parent.
Something similar as Tree-Style Tabs

Thanks!

**Comment by danielmotaleite** [comment] 2017-08-15 11:36
+1 to this

**Comment by bwinton** [comment] 2017-08-15 13:32
Dupe of #96.  Thanks for the comment!

**Closed by bwinton** 2017-08-15 13:32 UTC
