### ISSUE TITLE
search bar disappears after I uninstall tabcenter

### ISSUE THREAD

**Issue by cinna01** [bwinton/TabCenter#686] opened 2016-10-07 00:18 UTC
Ubuntu 16.04; firefox 49.0
In order to get my search bar back after uninstalling tabcenter, I use menu->customize to put the search bar into a toolbar. That is expected and everything works fine. The next time I start firefox the search bar is gone from the toolbar again and I have to redo menu>customize sequence to get my search bar into a tabbar. This happens over and over.

**Comment by ericawright** [comment] 2016-10-07 13:46
could you provide some screenshots of before and after?

**Comment by cinna01** [comment] 2016-10-07 16:04
screen shots:

**Comment by ericawright** [comment] 2016-10-07 16:54
They didn't seem to come through. You can drag and drop the images into the comment on Github.

**Comment by cinna01** [comment] 2016-10-07 17:25
screen shots:

![screenshot0-no searchbar is present](https://cloud.githubusercontent.com/assets/22670754/19198998/894b58e0-8c87-11e6-9ea2-86315025fcde.png)
After removing tabcenter, there is no searchbar which is what I expected.

![screenshot1-searchbar is on customize page](https://cloud.githubusercontent.com/assets/22670754/19198999/8963a36e-8c87-11e6-8a59-c078312d4f34.png)
Searchbar is available on the customize page at bottom.

![screenshot2-move searchbar to toolbar top right](https://cloud.githubusercontent.com/assets/22670754/19199000/897ef63c-8c87-11e6-855d-4fec66ff4e18.png)
Move the searchbar into a toolbar.

![screenshot3-exit from customize page-searchbar still at top right](https://cloud.githubusercontent.com/assets/22670754/19199001/898e6a0e-8c87-11e6-9672-9ad2d95bb40b.png)
After closing the customize page, the searchbar is in the toolbar.
So far, everything is ok.

![screenshot4-after browser restart-searchbar has disappeared from toolbar](https://cloud.githubusercontent.com/assets/22670754/19199004/89a3b0c6-8c87-11e6-9c1a-2b11109e4d63.png)
After restarting the browser, the searchbar is no longer in the toolbar.

![screenshot5-after browser restart-searchbar is back on customize page](https://cloud.githubusercontent.com/assets/22670754/19199002/899f6c8c-8c87-11e6-9ac9-886bee2f4f55.png)
The searchbar is back on the customize page.

**Comment by cinna01** [comment] 2016-10-11 19:48
cinna01 did not close this issue; it is still an issue.

**Comment by cinna01** [comment] 2016-10-11 19:54
what I mean is: cinna01 did not intentionally close this issue. I is still an issue. The last thing I did was to deactivate all of my extensions and try to put the search bar into the toolbar; this had no effect.

**Comment by cinna01** [comment] 2016-10-15 14:22
I re-installed firefox, which had no effect. I then removed test pilot, and I was able to get my search bar back.

**Comment by ericawright** [comment] 2016-10-17 13:49
Thank you @cinna01 I'd like to keep this open for now until we get a chance to fix it or figure out what the was causing it.

**Comment by ericawright** [comment] 2017-05-16 20:20
closing as I can't reproduce

**Closed** 2017-05-16 20:19 UTC
