### ISSUE TITLE
CTRL+PageUp/PageDown behaviour counterintuitive when reverse order is active

### ISSUE THREAD

**Issue by marcosins** [bwinton/TabCenter#1071] opened 2017-05-01 23:35 UTC
### Platform
Firefox versión: 53.0
Build ID: 20170418123315
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0
OS: Linux 4.4.0-77-generic - Xubuntu

### Current behaviour

![firefox-tabs](https://cloud.githubusercontent.com/assets/14003389/25598842/dcf8c3c4-2ead-11e7-9c86-b8eda8ab9300.png)

When option "Reverse tabs order" is active, CTRL+Page**Down** changes to the **next tab above** the current tab. Same for CTRL+Page**Up**, it changes to **previous tab below** the current tab.

### Expected behaviour
CTRL+PageUp should change to next tab, above current.
CTRL+PageDown should change to previous tab, below current.

**Comment by SoftVision-CiprianMuresan** [comment] 2017-05-02 09:24
Hi @marcosins, thanks for the report. However this is a dupe of #815.

**Closed by SoftVision-CiprianMuresan** 2017-05-02 09:24 UTC
