### ISSUE TITLE
Painfully long tab close animation

### ISSUE THREAD

**Issue by UserNaem** [bwinton/TabCenter#895] opened 2017-01-16 22:01 UTC
Pressing middle mouse button to close a tab initiates a ~400 ms long animation, which means it's impossible to quicky close a bunch of tabs with several middle mouse clicks in a row. Please add an option to disable this animation.

**Comment by Keith94** [comment] 2017-01-19 19:07
Dupe of #740.

**Closed** 2017-01-20 16:49 UTC
