### ISSUE TITLE
Close button does not appear if the width is reduced

### ISSUE THREAD

**Issue by rockoder** [bwinton/TabCenter#968] opened 2017-02-28 05:01 UTC
This is a great feature and find it useful to me. I have anywhere between 80 to 150 tabs open during the weekdays which I clear up on weekend. TabMixPlus is one of the first plugin that I install on Firefox.

I prefer to have the width of the sidebar as minimum as possible (as long as I can able to identify what tab it is). Attached are two screenshots which are the most common width I am using.

However, in both the cases, the close button does not appear when I hover the mouse over it. **There is just no way to close the tab using mouse left click.** I need to increase the width for close button to appear.

At least provide a common close button at the top, to close the current tab.

![screen1](https://cloud.githubusercontent.com/assets/2136164/23392486/fdfc281e-fda1-11e6-99cb-cdff718d83ec.png)
![screen2](https://cloud.githubusercontent.com/assets/2136164/23392485/fdf51376-fda1-11e6-8692-4417a1ffb862.png)

**Comment by SoftVision-CiprianMuresan** [comment] 2017-02-28 12:33
Hi @rockoder, thanks for reporting this, however it is a dupe of #836. 
There are 2 other ways in which you can close tabs:
1. You can use the mouse wheel click. This closes the tab the mouse pointer is hovering on.
2. Ctrl+w or Cmd+w is a keyboard shortcut for closing the focused tab.

**Closed by SoftVision-CiprianMuresan** 2017-02-28 12:33 UTC
