### ISSUE TITLE
Expanded view is useless

### ISSUE THREAD

**Issue by JojoJojoJoey** [bwinton/TabCenter#535] opened 2016-08-17 02:41 UTC
No offence, but expanded view is a nuisance. Webpage preview does not show, so what I can get is a small icon placed in the middle of a large blank rectangle. The URL line is redundant, as identifying a tab using URL is definitely counter-intuitive. So now in order to keep my tab center neat and tidy, I am encouraged to leave tabs open so that I will have sufficient number of tabs to keep the compact view.

I know this thing is experimental, but I just can't help feeling that this feature is worthless.

![screenshot 2016-08-17 10 41 58](https://cloud.githubusercontent.com/assets/20691604/17722753/380ab824-6467-11e6-883d-e5d16859dbbf.jpg)

**Comment by mathroc** [comment] 2016-08-17 09:01
that's a bit harsh, the feature is not worthless, it could even be very nice when polished. but i'd like an option to always have the compact tab view too

**Comment by bwinton** [comment] 2016-08-17 12:30
I agree with @mathroc, and we have been polishing it since the last release.  More importantly, @JojoJojoJoey, the dismissive tone used in this issue is not welcome here.  If you can't be civil and constructive, please refrain from commenting.

Finally, I'm closing this as a duplicate of #439.

**Closed by bwinton** 2016-08-17 12:30 UTC
