### ISSUE TITLE
Address bar trimmed in Full Screen mode

### ISSUE THREAD

**Issue by rwakulszowa** [bwinton/TabCenter#714] opened 2016-10-19 23:04 UTC
Hey,
I noticed a problem when using TabCenter in Full Screen mode (F11). The address bar is trimmed proportionally to the width of the tab panel.
![tab_normal](https://cloud.githubusercontent.com/assets/10756296/19540548/9502756e-9660-11e6-9c6d-30e1c40384e1.png)
![tab_fs](https://cloud.githubusercontent.com/assets/10756296/19540547/94fbc4f8-9660-11e6-97d8-28307bad4d25.png)
When using FS mode, TabCenter automatically enters the "hide when not used" mode (or so it seems), so I guess that may be causing the problem.

**Comment by ericawright** [comment] 2016-10-20 14:06
Thank you, this is a dupe of #705, which will be fixed with #711

**Closed by ericawright** 2016-10-20 14:06 UTC
