### ISSUE TITLE
Panel doesn't reorganize itself after closing tabs

### ISSUE THREAD

**Issue by txai** [bwinton/TabCenter#1068] opened 2017-04-28 01:57 UTC
If you have 3 tabs and close the middle one there will be a blank space where the tab was.

**Comment by SoftVision-CarmenFat** [comment] 2017-04-28 11:18
Hi @txai and thanks for the report. 
However this is a dupe of #1062 and a fix is already merged in the latest master.

**Closed by SoftVision-CarmenFat** 2017-04-28 11:18 UTC
