### ISSUE TITLE
TabCenter is over Firefox's UI

### ISSUE THREAD

**Issue by Defman21** [bwinton/TabCenter#1064] opened 2017-04-22 11:36 UTC
I'm not able to see anything under TabCenter (e.g. Go back button). It hides a part of any website as well. See screenshot:

![image](https://cloud.githubusercontent.com/assets/7100645/25304096/d7279e9e-2768-11e7-9967-a11e6c1a5c79.png)

(I'm not using Htitle, lack of window decorations is a glitch of a screenshot tool I use to capture windows)

Firefox 55.0a1 (2017-04-22) (64-bit).

**Comment by MikkCZ** [comment] 2017-04-22 12:25
The same for me happened just now after installing the latest nightly updated (Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0 ID:20170422100218 CSet: 7d85b081bfabe91dbf18a421f1eee2a32f335823). Yesterday everything worked just fine.

**Comment by Defman21** [comment] 2017-04-22 12:31
Yep it were working for me before today's update, too.

**Comment by SuperTux88** [comment] 2017-04-22 15:18
I have the same problem, and I checked it with `mozregression`. The regression happened somewhere here:

https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=ff6abe20041933a67f636b748ed698e9616a6833&tochange=bf2654d9c37523800d2f27c7e8c12eac40873f7f

(`mozregression` then exits with "Oh noes, no (more) inbound revisions :(", so I don't have it more accurate.)

**Comment by denschub** [comment] 2017-04-22 18:28
This is fallout from landing [bug 1355331](https://bugzilla.mozilla.org/show_bug.cgi?id=1355331), which moved the default sidebar position to the right (that's part of Photon).

**Comment by bgrins** [comment] 2017-04-24 17:27
Bug 1355331 has been backed out, so this should be fixed in tomorrow's nightly

**Comment by denschub** [comment] 2017-04-24 17:29
Thanks Brian!

**Closed** 2017-04-26 12:25 UTC
Labels: p1

**Comment by SoftVision-CarmenFat** [comment] 2017-04-28 12:41
Since bug 1355331 has been backed out, the issue is no longer reproducible on the latest version of Tab Center (built on 4/28/2017) using latest Nightly 55.0a1 (28-04-2017).
