### ISSUE TITLE
Can Firefox theme be applicable on TabCenter ?

### ISSUE THREAD

**Issue by Nemesis31** [bwinton/TabCenter#1030] opened 2017-03-24 17:29 UTC
Hello there,

i'm using Firefox **Black** script with Stylis and [a web browser renaissance](https://addons.mozilla.org/fr/firefox/addon/a-web-browser-renaissance/) (theme), and the background of TabCenter is..... **white** :)

My question is:  is it possible for TabCenter to have the **same theme as Firefox** ?

There a screenshot:
![tabcenter_theme_question](https://cloud.githubusercontent.com/assets/16542379/24306115/b7565a48-10bf-11e7-9a74-41f01784188b.png)

BTW, thanks for the great work ;)

**Comment by Nemesis31** [comment] 2017-03-24 17:43
So, i found that my theme "sucks" and doesn't consider the TabCenter. I changed my actual theme to Dark Fox and.... the background of TabCenter is black.

Sorry for this **useless** issue.

**Comment by bwinton** [comment] 2017-03-24 17:54
No worries!  At least it isn't yet another duplicate of #7…  😉

**Closed by bwinton** 2017-03-24 17:54 UTC
