### ISSUE TITLE
When rearranging bookmarks in the bookmarks toolbar, the arrow appears far below the toolbar 

### ISSUE THREAD

**Issue by mvard** [bwinton/TabCenter#645] opened 2016-10-01 09:17 UTC
I'm running Firefox 49.0 on Fedora 24. This issue appears only when using the add-on and what happens is that the bi-directional arrow showing where the bookmark will be positioned appears far below the toolbar while using Tab Center.

**Comment by Keith94** [comment] 2016-10-01 10:20
Dupe of #147

**Closed** 2016-10-01 13:33 UTC
