### ISSUE TITLE
Searchig with numerical values in TabCenter shows New Tab as result

### ISSUE THREAD

**Issue by mMARUF** [bwinton/TabCenter#837] opened 2016-12-08 13:52 UTC
In the search bar of TabCenter , if any numerical values is used as search keyword, then New Tab comes up as a result. This problem also occurs with using some of the alphabets from the keyboard.

This problem is found in latest Nightly 53

Attachment :  https://drive.google.com/open?id=0B75_JfziYeofMVVXMU1INW5zazA

**Comment by ericawright** [comment] 2016-12-08 20:37
I cannot reproduce on mac... it looks like you are on windows, can you let me know which version?

**Comment by mMARUF** [comment] 2016-12-09 10:08
WIndows 7 , 64 Bit

**Comment by SoftVision-PaulOiegas** [comment] 2016-12-09 14:23
I can confirm this also on Windows 10 x64 but as Erica said, it does not reproduce on Mac OS.

![numbers and new tabs](https://cloud.githubusercontent.com/assets/17258026/21052019/902bad56-be2b-11e6-9791-dd0fad7f55ec.gif)

**Comment by ericawright** [comment] 2017-04-06 14:36
seems to be fixed now

**Closed by ericawright** 2017-04-06 14:36 UTC

**Comment by SoftVision-PaulOiegas** [comment] 2017-04-07 13:26
It seems so for the normal case, but I managed to replicate this behavior now with pinned tabs. But only in the specific case from https://github.com/bwinton/TabCenter/issues/1050#issuecomment-292534728. 
I think we can leave this closed and will tackle the new behavior in the new issue.
