### ISSUE TITLE
Unable to drag link/image inbetween two tabs to open in new tab

### ISSUE THREAD

**Issue by zvory** [bwinton/TabCenter#967] opened 2017-02-28 01:16 UTC
Often, I open up links or images by clicking and dragging them to my list of tabs. With regular tabs, you can click and drag a link/image, and place it in between two tabs. This is very useful; I use it multiple times a day.

This is impossible in tab center. It would be nice if there was a couple pixel area where dragging a link/image in between two tabs would open a new tab with the link/image loaded inbetween these two tabs.

Having full feature parity (is that the right phrase?) with regular tabs would be nice.

I hope I'm getting what I mean across clearly.

[Discourse link](https://discourse.mozilla-community.org/t/cant-drag-link-image-between-two-tabs/13966)

**Comment by ericawright** [comment] 2017-02-28 15:30
This works if you drag it onto an empty space in the tab bar, but yes, it would be nice to be able to drag it between tabs as well.

**Comment by zvory** [comment] 2017-02-28 15:42
Yup, you can drag to an empty space, but 90% of the time when I'm dragging
a link/image, positioning is important. It's a fast way to view an image in
a new tab, or open a link in a specific position.

And if you have a lot of tabs open, I'm not even sure you get the empty
space.

**Comment by Keith94** [comment] 2017-03-01 05:04
Duplicate of #258

**Closed** 2017-03-01 14:23 UTC
