### ISSUE TITLE
Localization string on hover

### ISSUE THREAD

**Issue by quentinlamamy** [bwinton/TabCenter#924] opened 2017-02-14 12:26 UTC
On hover of the sidebar shrink button i actually have a localization string ${strings.sidebarShrink}

![sans titre](https://cloud.githubusercontent.com/assets/6804887/22928926/3c636138-f2b9-11e6-8cee-dd509b62b50c.jpg)

**Comment by SoftVision-CiprianMuresan** [comment] 2017-02-14 12:29
Hi @quentinlamamy, thanks for reporting this, however it is a duplicate of #866.

**Closed by SoftVision-CiprianMuresan** 2017-02-14 12:29 UTC

**Comment by quentinlamamy** [comment] 2017-02-14 12:34
Sorry for the duplicate

---

Le 14.02.2017 13:29, Ciprian Muresan a écrit :

> Hi @quentinlamamy [1], thanks for reporting this, however it is a duplicate of #866 [2]. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4].
 

Links:
------
[1] https://github.com/quentinlamamy
[2] https://github.com/bwinton/TabCenter/issues/866
[3]
https://github.com/bwinton/TabCenter/issues/924#issuecomment-279694909
[4]
