### ISSUE TITLE
Context menu options lost on bookmarks toolbar when TabCenter is enabled.

### ISSUE THREAD

**Issue by jmmosher1** [bwinton/TabCenter#965] opened 2017-02-27 00:24 UTC
I installed Firefox Test Pilot today and activated TabCenter. I tried to right click a bookmark in my bookmarks toolbar to open a bookmark in a new tab I was unable to select anything in the context menu. Moving tabs back to the top did not solve the issue. Disabling TabCenter did resolve the issue. 

Using Windows 10 Home, Version 1607, OS Build 14393.693
Firefox 51.0.1 (32-bit)
TabCenter 1.29.0

![image](https://cloud.githubusercontent.com/assets/12648071/23345210/e6c24c4e-fc4f-11e6-83cf-edd98c328409.png)

**Comment by SoftVision-CiprianMuresan** [comment] 2017-02-27 07:29
Hi @jmmosher1, thank you for reporting this, however it is a dupe of #583.

**Closed by SoftVision-CiprianMuresan** 2017-02-27 07:29 UTC
