### ISSUE TITLE
Enabling and disabling Tab Center breaks CustomizableUI making Universal Search imposible to be enabled / disabled 

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [bwinton/TabCenter#479] opened 2016-08-02 17:07 UTC
[Steps]:
1. Go to https://testpilot.firefox.com page.
2. Click on the big green "Install the Test Pilot Add-on" button.
3. After the installation chose the "Tab Center" experiment and "Enable" it.
4. Disable the Tab Center experiment and return to Homepage.
5. Choose the "Universal Search" experiment and "Enable" it.
6. Observe the browser address bar after experiment is enabled.

[Expected result]:
The browser address bar is unified with the search bar.

[Actual result]:
The browser address bar remains unchanged.

[Notes]:
- This issue also occurs if the Universal Search is already enabled when disabling Tab Center. But in this case the unified bar won't split after disabling Universal Search.
- The same issue seems to cause also this issue from Test Pilot https://github.com/mozilla/testpilot/issues/1164 . Where having Tab Center installed before Universal Search, won't remove the last one at Test Pilot uninstall.

**Comment by chuckharmston** [comment] 2016-08-12 16:03
This is apparently still reproducible, per: https://bugzilla.mozilla.org/show_bug.cgi?id=1294564#c2

**Comment by bwinton** [comment] 2016-08-16 14:54
There hasn't been a release since this was fixed.  If people can reproduce it with the latest code from github, then please re-open this issue.  Otherwise I continue to claim that it has been fixed by the referenced commit.

**Closed by bwinton** 2016-08-16 14:54 UTC

**Comment by SoftVision-PaulOiegas** [comment] 2016-08-18 15:37
I can confirm that this was fixed after testing with a custom build made today from github repo.
Tested with both experiments custom builds but also with the Tab Center custom one and Universal Search build from Test Pilot dev.
