### ISSUE TITLE
Dragging pinned tab to reposition broke

### ISSUE THREAD

**Issue by zvory** [bwinton/TabCenter#1009] opened 2017-03-11 18:47 UTC
I was moving my tabs around, or something, when things broke. 

![cropped0](https://cloud.githubusercontent.com/assets/4392164/23825908/93e37014-0660-11e7-9370-1d4565f3a842.png)

One tab got shifted up by a couple of pixels, and stayed there. Using my mouse to click and drag any tabs didn't work. I opened up some new tabs, the smaller tabs thing triggered, but the bug was still present.

I could use ctrl+shift+pgup/pgdown to move tabs though. Including, i think, the tab that was broken.

![cropped1shifted](https://cloud.githubusercontent.com/assets/4392164/23825910/95596110-0660-11e7-8ae3-b7e17303b2c2.png)

Some time later, the problem fixed itself, I don't know how.

Firefox 52.0 (64-bit), Ubuntu 16.10

**Comment by SoftVision-CiprianMuresan** [comment] 2017-03-13 12:22
Hi @zvory, thanks for reporting this. 
However, I haven't been able to reproduce this behavior on Windows or Ubuntu 14.04 with Tab Center installed from Test pilot. 

Do you, by any chance, have any other tab related add-ons that might interfere with Tab Center? (see #464 for all add-ons that are incompatible with Tab Center)

**Comment by zvory** [comment] 2017-03-13 13:37
I don't have any of those add-ons. I doubt you'd be able to easily reproduce this bug, it feels rare.

If I recall correctly, there was a stutter of lag right as the bug happened. It's possible all the stuff i had open (some relatively heavy webpages) caused that lag, and that caused the bug, or the bug caused the lag. I don't know if that information is useful.

**Comment by SoftVision-CiprianMuresan** [comment] 2017-03-13 14:03
Thanks for the quick response, I'll try to load an unnatural amount of tabs in order to create some lag. I'll see if I can get them stuck this way.

**Comment by zvory** [comment] 2017-03-13 14:41
To be clear, I had a perfectly natural amount of tabs open, it was just enough of them/they were intensive enough (multiple docs, google play music, other crap) that there was some lag.

**Comment by ericawright** [comment] 2017-05-16 20:23
we haven't ever been able to reproduce this, and the way that tabs are dragged has changed a lopt since this, so closing for now.

**Closed by ericawright** 2017-05-16 20:23 UTC

**Comment by zvory** [comment] 2017-06-01 01:07
this has happened again as recently as four days ago. i do not have any information on the platform or version of firefox however.
