### ISSUE TITLE
"Open in new tab" tabs should be placed after the current tab (revert the change to put them earlier in the tab stack)

### ISSUE THREAD

**Issue by folz** [bwinton/TabCenter#655] opened 2016-10-03 23:29 UTC
As of the latest update, "Open in new tab" (e.g., ctrl-click links) tabs will open above the current tab. Screenshots below (blue-striped github tab is the current tab).

To navigate to the new tab, I now have cycle earlier in my tab history with Ctrl-Shift-Tab. This breaks convention from Firefox and all other browsers that new tabs are next after the current one. It also interrupts my decade-old muscle memory about which keys to press.

Further, this makes browsing any site with links difficult (Facebook, Hacker News, etc) because ctrl-clicking the link/comments will open the tabs earlier than the current tab, but closing the current tab will open the tab after the current tab. E.g., given the tab stack

HN <-- current
Gmail

Clicking on a HN story and comments gives me the new stack

Comments
Story
HN <-- current
Gmail

And closing the HN tab gives me

Comments
Story
Gmail <-- Current

In previous versions of this addon, and in vanilla firefox, closing the HN tab would take me to the story tab because it would have been created after the HN tab.

To clarify, this is not the same as issues talking about whether new tabs (ctrl-T) open at the top or bottom of the stack. I personally prefer your change to make new tabs at the top by default.

-- Screenshots --

Before:
![screenshot from 2016-10-03 16-19-51](https://cloud.githubusercontent.com/assets/299281/19057561/92046e54-8985-11e6-8e4e-69d5ce1c5bf2.png)

After a ctrl-click on the GitHub logo:
![screenshot from 2016-10-03 16-22-14](https://cloud.githubusercontent.com/assets/299281/19057569/a61298c6-8985-11e6-8f1b-eccfb2fe675f.png)

**Comment by Hoverbear** [comment] 2016-10-04 10:04
Confirming this behavior is unexpected and a counter-intuitive.

In Firefox without Tab Center ctrl+clicking a link means I can tab to it easily. With this addon I now need to shift+tab.

**Comment by xrogaan** [comment] 2016-10-04 10:18
This behavior is actually intended, see #652

**Comment by bartlibert** [comment] 2016-10-04 13:24
I dont' think this is intended, or at least it should not be. I had the "Tabs on Top" setting enabled before, so changing it to default in #652 should not have changed anything for me.
The difference is that it used to be this way:
- Open new tab via the button/Ctrl-t: opened on top
- Click on a link that opens a new tab: opened below the current tab.

Now it's always opening above the current ab.

**Comment by ericawright** [comment] 2016-10-04 13:28
@folz yes, we did change the default behavior, which was intended and should no affect you. What you are noticing is the result of #544, which was done as a response to this discussion #410. This behavior is also intended.

**Comment by vmoutoussamy** [comment] 2016-10-04 13:36
Sorry but could someone help me on setting "always open tab in any situation at bottom"? I don't see where I can change the setting/preference. thanks

**Comment by dannyhajj** [comment] 2016-10-04 15:18
@ericawright In that case, shouldn't the "Close Tabs Below" context menu become "Close Tabs Above"? Though I wonder if it would become confusing since the tabs above would contain the pinned tabs as well.
_In "normal Firefox" it's "Close Tabs to the right"._

**Comment by ericawright** [comment] 2016-10-04 15:20
@dannyhajj in this case, no. That menu item closes all tabs with a larger index, which has to do with the tab's position in the list and not the order they were opened. 
If you would like it to behave that way, perhaps open a new feature bug and see if others agree with you?

**Comment by folz** [comment] 2016-10-04 18:55
Thanks for the comments. Since this seems to be intended behavior, I'm re-titling this as a feature bug. Let's see if anyone agrees with me :^)

Firefox has always placed "new" tabs after the current tab in the horizontal tab row. In my experience, when software moves something from top-horizontal to left-vertical, anything that was left-to-right becomes top-to-bottom. This change treats new tabs as bottom-to-top but the rest of Firefox's navigation treats tabs as top-to-bottom (e.g. default behavior of Tab/Shift-Tab, new tab focus after pressing Ctrl-W, etc)

If Tab Center wants to reverse that convention, there's more to it than just changing the spawn order. For example, Ctrl-W's tab focus should show the tab above the closed tab if possible. Maybe change the direction of Tab/Shift-Tab? Add a "close all tabs above" menu option, since now above means newer?

(I don't think this has anything to do with #652, which changes Ctrl-T new tabs from opening at the very bottom of the stack to the very top of the stack. I still like that change.)

**Comment by dannyhajj** [comment] 2016-10-04 19:18
I agree with @folz. @ericawright I'll do that, though I think it's better to wait and see how this feature request is received before opening the new feature bug.

**Comment by ericawright** [comment] 2016-10-04 19:36
@folz @dannyhajj the reason I would disagree with you is that when we set preferences to open the tabs below, it will behave as you describe default: the tabs open at the bottom and one below active tab (=right side of the tab) and you can `ctrl-tab` to them. 
If a user wants the opposite behavior, and opens the tabs on the top it is a little odd to have the opposite of one, but not the other - no? So opposite regular tab behavior, new tabs open at top (=left side) and one above active tab (=left of active tab).

**Comment by kirbysayshi** [comment] 2016-10-04 20:27
This just switched on me and I thought something was broken, I didn't know it was intentional.

The problem might not be putting new tabs on top, but more how the other tabs are ordered. I have around 30 existing tabs, and they're in the same order they were yesterday before this change was made. Seems like they should be reversed (newest on top) for this change to make sense. Right now it's a very strange cognitive dissonance: I have newish tabs on the bottom of the tab list, but opening a new tab from that tab makes the tab center jump all the way up to the top. There is no spatial relationship between time and tab order right now.

So _probably_ just reversing the existing tab order would make any inconsistencies go away! It's basically thinking about rotations of the default top-tabs going counter-clockwise into the tab center (new behavior), or clockwise (previous, open at bottom behavior). But with existing tabs it's _both_!

Regardless, I'm really liking Tab Center so please keep up the good work :)

**Comment by Hoverbear** [comment] 2016-10-04 20:31
I think the main issue, at least for me, is the unexpected behavior of ctrl+tab and shift+ctrl+tab becoming, in a sense, "backwards" when using this addon.

Without the addon:

* Ctrl+tab -> "Newer" tab
* Shift+Ctrl+tab -> "Older" tab

With addon:

* Ctrl+Tab -> "Older" tab
* Shift+ctrl+tab -> "Newer" tab.

The behavior of Firefox is changed, when the addon appears at first glance to be purely a UI change. It seems strange that the default behavior of an officially sanctioned Firefox addon would be to *reverse* the default behavior existing in Firefox, and require the user to configure a setting to go back to what is the 'normal' default.

**Comment by Cadille** [comment] 2016-10-04 20:39
Definitely agreeing with @folz here, at least on "open in new tab" behavior. Given that pinned tabs are at the top (in the horizontal tab bar, they were the left most tabs), it makes the most sense to me to have links open to tabs below the current one.

The best thing to do, in my opinion, is to decide whether the equivalent left to right behavior is translated to bottom to top or top to bottom behavior. If it's top to bottom, pinned tabs should be up top, new tabs should open at the bottom (perhaps with the option to change it to opening at the top or below the current tab for those who have large numbers of tabs), and opening links in new tabs should place them directly below the current one.

Obviously, if you want bottom to top functionality, simply reverse the directions - pinned tabs are now at the bottom, new tabs open at the top, and links open in tabs above the current one, again with the option to change the behavior of the latter two if the user has a large number of tabs.

I think it's important to have the default behavior have a consistent top to bottom or bottom to top flow because I predict that most people will usually have few enough tabs to fit them all on the tab pane without needing to scroll. For those (like myself) who have lots of tabs, the ability to change that behavior to better suit them is also very important.

**Comment by folz** [comment] 2016-10-04 21:01
It looks like there are two issues in this thread:

1) Switching from top-to-bottom to bottom-to-top breaks convention.
2) We didn't realize this was intended.

For 2., I created #667 to request that UI/UX changes are accompanied by a small note to the end-user. For this issue, let's keep discussion to 1.

**Comment by ncalexan** [comment] 2016-10-04 21:56
> This just switched on me and I thought something was broken, I didn't know it was intentional.

I think this is significant.  There's an option now, and it switched without warning.  That's a bad experience, even when I grow to like the new behaviour.  It's really jarring that Ctrl+W and Ctrl+Tab just stop doing what you expect.

**Comment by Maeyanie** [comment] 2016-10-05 00:04
I agree with this "feature" being a bad idea. Pre-existing tabs were created being organized as later in the list means later in time, and suddenly Tab Center reverses this sorting, without reversing the actual order of tabs. Given Tab Center is mostly useful for people with lots of tabs, this would be a problem.

If anything, I would recommend changing this to an option and defaulting to the expected Firefox behavior of opening new tabs after exiting ones.

**Comment by db48x** [comment] 2016-10-05 00:32
I'm not sure yet if it's better or worse, but it was definitely surprising. It was also sneakily surprising, because it took a fair amount of time to notice what was actually happening. In the mean time tabs were misplaced or lost. Now that I understand what is going on it won't be a problem.

Since this is only in testing I don't really have a problem with the change, but I would recommend not making that sort of change once this reaches a wider audience.

**Comment by MrJustMe** [comment] 2016-10-05 09:22
I thinks i like the current behaviour, anyway...
What about to?:
1.- An option to change from the current behaviour to the previous one, perhaps could be nice to change between both. Perhaps in the content menu of any tab and in general settings?.
2.- Modify the current behaviour of tab button and keyboard shortcuts according with the option selected by default?.

**Comment by ericawright** [comment] 2016-10-05 13:24
@db48x @folz (and others) As for the surprise, that was unintentional. We were under the impression it would only affect new installs and not change peoples' current preferences, sorry about that.

**Comment by dannyhajj** [comment] 2016-10-05 17:10
@ericawright I think it's a good thing that happened though, or this discussion probably wouldn't have happened (I had only started using Test pilot as a whole yesterday, so I would have been affected either way :stuck_out_tongue:).

May I suggest the following: (Table taken from comment by @mathroc's [comment on #410](https://github.com/bwinton/TabCenter/issues/410#issuecomment-240404612)

 | Open on Top | Don't Open on Top
---|---|---
New Tab Button | Open on top | Open on bottom
Link in Page | **Open below current tab** | Open below current tab
External App | Open on top | Open on bottom

Another note, the users who +1'ed @mathroc's comment also +1'ed @mlissner's [comment](https://github.com/bwinton/TabCenter/issues/410#issuecomment-240466102) which suggests this change.

**Comment by bwinton** [comment] 2016-10-05 17:13
I dunno.  That seems backwards to me.  "Newer tabs are always above, except when they're below."  😝

**Comment by mlissner** [comment] 2016-10-05 17:58
> "Newer tabs are always above, except when they're below."

I think the way to think about this is that every time you open a new tab from scratch, you get a new context at the top of your stack. So this is what happens every time you hit the New Tab button or open something from an external app. Once you have that context, if you're clicking a link within a page, those pages go below your current context. 

The net of this is that newer contexts are higher, but that subtabs of those contexts are nested below the tab that started the context. 

I think this maps to mental models really well. For example, I want to research the country of Turkey, so I press "New Tab". I get a new tab at the top of my stack since that's currently my highest priority. As I'm researching, I start diving into smaller and smaller topics within that broad topic. I started out researching Turkey, but now I realize I don't know what the Ottoman Empire is and I'm curious to read more about refugees, so I open those topics in new tabs. Since Ottoman Empire and refugees are subtopics of my initial research task, Turkey, they go *below* Turkey.

My tabs now look like:

 - Turkey
 - Ottoman Empire
 - Refugees

If this logic were reversed, you'd end up with a stack like:

 - Refugees
 - Ottoman Empire
 - Turkey

Reading from top to bottom, that's the opposite of the order of your research, and might make you think that you were researching Refugees, not Turkey.

**Comment by bwinton** [comment] 2016-10-05 18:01
That is _a_ way to think about it, but it doesn't seem like the simplest way, particularly since there's no distinguishing which tabs are in which stacks…

As well, we're planning on changing the default to "Open new tabs below the current tab", which will hopefully sidestep this problem for most people.

**Comment by dannyhajj** [comment] 2016-10-06 07:40
> As well, we're planning on changing the default to "Open new tabs below the current tab", which will hopefully sidestep this problem for most people.

I think this is a good idea. Although I liked the fact that new tabs from external apps and the new tab button would open at the top.

---
This is a whole different solution that I think can help with this problem; But what about keeping pinned tabs, pinned? As in scrolling the tabs in the tab bar would keep the pinned tabs visible. Just as the default tabs behavior works in stock Firefox. If this was the case, personally I wouldn't care if the tabs open at the top or bottom since my pinned tabs would still be visible no matter what.

_Actually, I'd probably prefer to open them at the bottom so that my <kbd>Alt</kbd>+<kbd>1-8</kbd> would always open the same tabs whether pinned or not. <kbd>Alt</kbd>+<kbd>9</kbd> always open the last tab so, this way, that shortcut would still be useful as well_

_I can open a new ticket about this if it others like this idea. But I'd like to point out an issue about this first that, vertically, there isn't enough space for tabs as there would be in a horizontal tab bar. But I don't know if that's a big issue, as I haven't checked the telemetry reports._

**Comment by MrJustMe** [comment] 2016-10-06 08:34
Open my pinned tabs at the bottom? I like the idea i think...

**Comment by laktak** [comment] 2016-10-18 11:59
@bwinton 

> As well, we're planning on changing the default to "Open new tabs below the current tab", which will hopefully sidestep this problem for most people.

If you do that, please implement it with an option that lets me select what I want.

**Comment by Maeyanie** [comment] 2016-10-18 14:11
It's already an option, though it's not obvious. You have to go into the Addons screen (or about:addons), then click the "Options" button beside Tab Center.
Then uncheck "[ ] Open Tabs Above" and you'll get the more traditional opening tabs below.

**Comment by laktak** [comment] 2016-10-25 09:41
@Maeyanie  thanks, I think I misunderstood that this referenced an old version. The current one still doesn't work quite right though, maybe this #709 explains is better.

**Comment by grahamperrin** [comment] 2017-05-27 11:23
Should this issue be marked as closed? 

I see (but have no recolleciton of using) the option, 

> [`    `] Reverse tab order
> `       `Newest tabs are on top
> `       `Tab shortcuts will move in reverse

**Closed** 2017-12-06 18:52 UTC
