### ISSUE TITLE
Going through Session Restore reverses the order of tabs

### ISSUE THREAD

**Issue by SimonSapin** [bwinton/TabCenter#771] opened 2016-11-08 16:35 UTC
I use Tab Center with the "Open tabs above" setting enabled, so that recently-used tabs (the ones I’m most likely to go back to) are near the top. Near the bottom are tabs that have been opened (but often not loaded) for a long time.

Whenever Firefox crashes (which is not often, but happens sometimes) and shows the "Session Restore" window on restart, after clicking "Restore" and recovering tabs, the order of non-pinned tabs is reversed. All my recently-used (and most likely to be used again) tabs end up near the bottom, far away from pinned tabs.

Lately I’ve started to use `pkill -f -9 firefox` when that happens to trigger the Restore Session screen again, so that two reversions cancel each other.

**Comment by ericawright** [comment] 2016-11-14 14:42
thanks, this is a duplicate of #716 which has been fixed and will be out with the next version

**Closed by ericawright** 2016-11-14 14:42 UTC
