### ISSUE TITLE
Close button shows up briefly when panel slides open

### ISSUE THREAD

**Issue by digitarald** [bwinton/TabCenter#106] opened 2016-05-04 17:03 UTC
The mouse hovers the close button while the panel moves out, causing some visual noise.

**Comment by bwinton** [comment] 2016-05-04 17:11
Definitely something we want to fix, but probably not going to happen in the next six days…  😃

**Comment by Keith94** [comment] 2016-08-03 09:28
Seems to be fixed by #478; can't reproduce anymore.

**Comment by bwinton** [comment] 2016-08-22 18:09
Closing as per previous comment.  😉

**Closed by bwinton** 2016-08-22 18:09 UTC
