### ISSUE TITLE
Hole left after page prevented closing

### ISSUE THREAD

**Issue by grahamc** [bwinton/TabCenter#1090] opened 2017-05-25 12:55 UTC
Reproduction:

1. Edited a page in Confluence but don't save
2. Press the "X" to close the tab
3. Get prompted "you didn't save, do you want to leave?"
4. Decide to stay on the page
5. A hole appears and the tab disappears in the sidebar, and the page remains open.
6. Close the page, and the hole remains.

Hovering over the hole, even after actually closing the tab, shows a box (like hovering over an image) 
that says the name of the Confluence page but clicking the hole takes you to the next open tab.

![screen shot 2017-05-25 at 8 53 08 am](https://cloud.githubusercontent.com/assets/76716/26450969/f190fb8a-4127-11e7-8732-9563612b1764.png)

**Comment by SoftVision-CiprianMuresan** [comment] 2017-05-25 13:14
Hi @grahamc, thanks for the report. However, this issue is a dupe of #1077 and was already fixed in the latest master. 
A new release is planned to land in the following days.

**Closed by SoftVision-CiprianMuresan** 2017-05-25 13:14 UTC

**Comment by grahamc** [comment] 2017-05-25 14:10
Ack! Thank you, sorry for the duplicate. I hadn't found that when I looked.
Thank you!
