### ISSUE TITLE
Context menu for bookmarks in Bookmarks Toolbar grayed out/deactivated

### ISSUE THREAD

**Issue by cyanfr** [bwinton/TabCenter#704] opened 2016-10-16 13:04 UTC
When TabCenter is active, all the options are grayed out when you right-click on a bookmark in the Bookmarks Toolbar.  Right-clicking on bookmarks in the standard bookmark management window works fine.  Only when right clicking on bookmarks in the Bookmarks Toolbar does the problem exist.

Deactivating TabCenter immediately restores the context menu in the Bookmarks Toolbar to normal functioning.

**Comment by danielkza** [comment] 2016-10-16 19:52
I'm seeing the same issue, Firefox 49.0 on Fedora 24.

**Comment by terrycloth** [comment] 2016-10-17 02:26
Looks like this is a duplicate of Issue #583.

**Comment by SoftVision-CiprianMuresan** [comment] 2016-10-17 10:17
@cyanfr, thank you for reporting this, however it is in fact a duplicate of #583.

**Closed by SoftVision-CiprianMuresan** 2016-10-17 10:17 UTC
