### ISSUE TITLE
After toggling sidebar open/closed, tooltip shows `${strings.sidebarShrink}`/`${strings.sidebarOpen}`

### ISSUE THREAD

**Issue by mystor** [bwinton/TabCenter#977] opened 2017-03-01 22:46 UTC
This is instead of the correct text.

![image](https://cloud.githubusercontent.com/assets/1261662/23484904/08c99668-fea7-11e6-8150-77ff7cf6368e.png)

**Comment by SoftVision-CiprianMuresan** [comment] 2017-03-02 07:50
Hi @mystor, thanks for the feedback. However this is a dupe of #834.

**Closed by SoftVision-CiprianMuresan** 2017-03-02 07:50 UTC
