### ISSUE TITLE
[Enhancement] Tabs on the right side

### ISSUE THREAD

**Issue by ShalokShalom** [bwinton/TabCenter#973] opened 2017-03-01 10:17 UTC
Can i place the tabs on the right side instead of the left?

**Comment by SoftVision-CiprianMuresan** [comment] 2017-03-01 10:23
Hi @ShalokShalom, thanks for the feedback. However this is a dupe of #7.

**Closed by SoftVision-CiprianMuresan** 2017-03-01 10:23 UTC

**Comment by ShalokShalom** [comment] 2017-03-01 10:54
Ok, thanks :)
