### ISSUE TITLE
Scrolling stopped working with Reverse Tab Order switched on

### ISSUE THREAD

**Issue by PauloGDPeixoto** [bwinton/TabCenter#995] opened 2017-03-09 09:12 UTC
Happened just yesterday, I don't recall doing anything special, but scrolling on the tabs stopped working. Today, after multiple removals and reinstallations of the addon, restarting firefox multiple times and even restarting the computer, I tried unchecking the Reverse Tab Order and it worked, but only with the default tab order, if I check the Reverse Tab Order again it stops working.
I'm using Firefox 52.0 x86_64 on Ubuntu. Please let me know if I can provide more information.

**Comment by SoftVision-CiprianMuresan** [comment] 2017-03-09 10:51
Hi @PauloGDPeixoto, thanks for the report. However it is a dupe of #988. A fix is already merged in the latest master.

**Closed by SoftVision-CiprianMuresan** 2017-03-09 10:51 UTC
