### ISSUE TITLE
Tabs temporarily disappear when I try to move one

### ISSUE THREAD

**Issue by pikestaff** [bwinton/TabCenter#587] opened 2016-08-26 15:55 UTC
![tab center](https://cloud.githubusercontent.com/assets/7683782/18011560/f2a3b6e2-6b72-11e6-9487-d368ad7fb2ce.gif)

This started happening when I reinstalled Tab Center a couple of days ago.  The issue persists when Firefox is closed and re-opened and occurs with any theme, including the default theme.  For some reason it seems to work fine in a Private Browsing window.  Thanks for the work on this addon!!

**Comment by Keith94** [comment] 2016-09-08 23:58
Do you have another add-on installed like Tab Utilities?

**Comment by Keith94** [comment] 2016-09-09 00:07
Yeah, there are some known compatibility issues with TMP... although strange that it works OK in private browsing 😕

**Comment by pikestaff** [comment] 2016-09-09 00:09
yeah, I couldn't figure out the private browsing part either.  Shame about TMP but thank you for the response. :)

**Comment by mhogerheijde** [comment] 2016-12-09 08:05
I have the same issue. I do not have any other tab add-ons installed. For me; this only happens after I start Firefox with its tabs from the previous session. Opening a new window and opening tabs on that one will show the intended behaviour of being able to reorder your tabs.

Multiprocess is not enabled; this is the (raw) content of my about:support

```json
{
  "application": {
    "name": "Firefox",
    "osVersion": "Linux 4.8.0-30-generic",
    "version": "50.0.2",
    "buildID": "20161130094630",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0",
    "safeMode": false,
    "supportURL": "https://support.mozilla.org/1/firefox/50.0.2/Linux/en-GB/",
    "numTotalWindows": 2,
    "numRemoteWindows": 0,
    "remoteAutoStart": false,
    "autoStartStatus": 7
  },
  "modifiedPreferences": {
    "accessibility.typeaheadfind.flashBar": 0,
    "browser.cache.disk.smart_size.first_run": false,
    "browser.cache.disk.hashstats_reported": 1,
    "browser.cache.disk.filesystem_reported": 1,
    "browser.cache.disk.capacity": 358400,
    "browser.cache.frecency_experiment": 1,
    "browser.cache.disk.smart_size.use_old_max": false,
    "browser.download.importedFromSqlite": true,
    "browser.download.manager.showAlertOnComplete": true,
    "browser.download.useDownloadDir": false,
    "browser.places.smartBookmarksVersion": 8,
    "browser.search.useDBForOrder": true,
    "browser.sessionstore.upgradeBackup.latestBuildID": "20161130094630",
    "browser.startup.homepage_override.mstone": "50.0.2",
    "browser.startup.homepage": "about:blank",
    "browser.startup.homepage_override.buildID": "20161130094630",
    "browser.tabs.warnOnClose": false,
    "browser.tabs.remote.autostart.2": true,
    "browser.tabs.animate": false,
    "browser.urlbar.userMadeSearchSuggestionsChoice": true,
    "dom.apps.lastUpdate.buildID": "20161025164528",
    "dom.apps.lastUpdate.mstone": "49.0.2",
    "dom.max_script_run_time": 40,
    "dom.max_chrome_script_run_time": 40,
    "dom.push.userAgentID": "8e6a62d330104919b19e8fa11746ce2d",
    "dom.apps.reset-permissions": true,
    "dom.mozApps.used": true,
    "extensions.lastAppVersion": "50.0.2",
    "font.internaluseonly.changed": false,
    "gfx.crash-guard.glcontext.driverVersion": "4.4.0 NVIDIA 340.96",
    "gfx.crash-guard.glcontext.deviceID": "GeForce GT 610/PCIe/SSE2",
    "gfx.crash-guard.glcontext.appVersion": "45.0",
    "gfx.crash-guard.status.glcontext": 2,
    "media.gmp-gmpopenh264.lastUpdate": 1471505730,
    "media.gmp-gmpopenh264.version": "1.6",
    "media.gmp-manager.lastCheck": 1481270126,
    "media.youtube-ua.override.to": "43",
    "media.gmp.storage.version.observed": 1,
    "media.gmp-gmpopenh264.abi": "x86_64-gcc3",
    "media.gmp-manager.buildID": "20161130094630",
    "network.predictor.cleaned-up": true,
    "network.auth.allow-subresource-auth": 2,
    "network.cookie.prefsMigrated": true,
    "places.history.expiration.transient_current_max_pages": 118039,
    "places.database.lastMaintenance": 1481101498,
    "plugin.state.libgnome-shell-browser-plugin": 0,
    "plugin.importedState": true,
    "plugin.disable_full_page_plugin_for_types": "application/pdf",
    "print.print_paper_width": "  8.27",
    "print.print_paper_size_unit": 0,
    "print.print_to_file": false,
    "print.print_orientation": 0,
    "print.print_margin_top": "0.5",
    "print.print_paper_height": " 11.69",
    "print.print_scaling": "  1.00",
    "print.print_unwriteable_margin_right": 25,
    "print.print_unwriteable_margin_left": 25,
    "print.print_paper_data": 0,
    "print.print_unwriteable_margin_bottom": 56,
    "print.print_paper_name": "iso_a4",
    "print.print_oddpages": true,
    "print.print_bgimages": false,
    "print.print_duplex": 0,
    "print.print_evenpages": true,
    "print.print_margin_left": "0.5",
    "print.print_shrink_to_fit": true,
    "print.print_margin_right": "0.5",
    "print.print_unwriteable_margin_top": 25,
    "print.print_bgcolor": false,
    "print.print_margin_bottom": "0.5",
    "print.print_in_color": true,
    "print.print_paper_size_type": 1,
    "print.print_page_delay": 50,
    "privacy.cpd.extensions-certpatrol": false,
    "privacy.donottrackheader.enabled": true,
    "privacy.sanitize.migrateClearSavedPwdsOnExit": true,
    "privacy.sanitize.migrateFx3Prefs": true,
    "security.tls.version.min": 0,
    "services.sync.declinedEngines": "adblockplus,passwords,tabs",
    "services.sync.lastPing": 1481186446,
    "services.sync.lastSync": "Fri Dec 09 2016 08:56:39 GMT+0100 (CET)",
    "services.sync.numClients": 3,
    "services.sync.engine.tabs": false,
    "services.sync.engine.passwords": false,
    "services.sync.engine.prefs.modified": false,
    "storage.vacuum.last.index": 1,
    "storage.vacuum.last.places.sqlite": 1479285635
  },
  "lockedPreferences": {},
  "javaScript": {
    "incrementalGCEnabled": true
  },
  "accessibility": {
    "isActive": false,
    "forceDisabled": 0
  },
  "libraryVersions": {
    "NSPR": {
      "minVersion": "4.12",
      "version": "4.12"
    },
    "NSS": {
      "minVersion": "3.26.2",
      "version": "3.26.2"
    },
    "NSSUTIL": {
      "minVersion": "3.26.2",
      "version": "3.26.2"
    },
    "NSSSSL": {
      "minVersion": "3.26.2",
      "version": "3.26.2"
    },
    "NSSSMIME": {
      "minVersion": "3.26.2",
      "version": "3.26.2"
    }
  },
  "userJS": {
    "exists": false
  },
  "crashes": {
    "submitted": [],
    "pending": 0
  },
  "sandbox": {
    "hasSeccompBPF": true,
    "hasSeccompTSync": true,
    "hasPrivilegedUserNamespaces": true,
    "hasUserNamespaces": true,
    "canSandboxMedia": true
  },
  "extensions": [
    {
      "name": "Adblock Plus",
      "version": "2.8.2",
      "isActive": true,
      "id": "{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}"
    },
    {
      "name": "Add-on Compatibility Reporter",
      "version": "2.2.3",
      "isActive": true,
      "id": "compatibility@addons.mozilla.org"
    },
    {
      "name": "Application Update Service Helper",
      "version": "1.0",
      "isActive": true,
      "id": "aushelper@mozilla.org"
    },
    {
      "name": "Certificate Patrol",
      "version": "2.0.14.1-signed.1-signed",
      "isActive": true,
      "id": "CertPatrol@PSYC.EU"
    },
    {
      "name": "Ghostery",
      "version": "7.1.1.5",
      "isActive": true,
      "id": "firefox@ghostery.com"
    },
    {
      "name": "LastPass",
      "version": "3.3.1",
      "isActive": true,
      "id": "support@lastpass.com"
    },
    {
      "name": "Lazarus: Form Recovery",
      "version": "2.3.1-signed.1-signed",
      "isActive": true,
      "id": "lazarus@interclue.com"
    },
    {
      "name": "Multi-process staged rollout",
      "version": "1.5",
      "isActive": true,
      "id": "e10srollout@mozilla.org"
    },
    {
      "name": "NoScript",
      "version": "2.9.5.2",
      "isActive": true,
      "id": "{73a6fe31-595d-460b-a920-fcc0f8843232}"
    },
    {
      "name": "Pocket",
      "version": "1.0.5",
      "isActive": true,
      "id": "firefox@getpocket.com"
    },
    {
      "name": "Self-Destructing Cookies",
      "version": "0.4.11",
      "isActive": true,
      "id": "jid0-9XfBwUWnvPx4wWsfBWMCm4Jj69E@jetpack"
    },
    {
      "name": "Tab Center",
      "version": "1.29.0",
      "isActive": true,
      "id": "tabcentertest1@mozilla.com"
    },
    {
      "name": "Test Pilot",
      "version": "0.9.1-dev-e42d9cb",
      "isActive": true,
      "id": "@testpilot-addon"
    },
    {
      "name": "Tile Tabs",
      "version": "14.9",
      "isActive": true,
      "id": "tiletabs@DW-dev"
    },
    {
      "name": "Ubuntu Modifications",
      "version": "3.2",
      "isActive": true,
      "id": "ubufox@ubuntu.com"
    },
    {
      "name": "Web Compat",
      "version": "1.0",
      "isActive": true,
      "id": "webcompat@mozilla.org"
    },
    {
      "name": "Add to Amazon Wish List Button",
      "version": "1.11",
      "isActive": false,
      "id": "amznUWL2@amazon.com"
    },
    {
      "name": "React Devtools",
      "version": "0.15.3",
      "isActive": false,
      "id": "@react-devtools"
    },
    {
      "name": "Web Developer",
      "version": "1.2.11",
      "isActive": false,
      "id": "{c45c406e-ab73-11d8-be73-000a95be3b12}"
    }
  ],
  "experiments": [],
  "graphics": {
    "numTotalWindows": 2,
    "numAcceleratedWindows": 0,
    "windowLayerManagerType": "Basic",
    "windowLayerManagerRemote": true,
    "supportsHardwareH264": "No",
    "currentAudioBackend": "pulse",
    "numAcceleratedWindowsMessage": [
      ""
    ],
    "adapterDescription": "nouveau -- Gallium 0.4 on NVD9",
    "adapterVendorID": "nouveau",
    "adapterDeviceID": "Gallium 0.4 on NVD9",
    "adapterRAM": "",
    "adapterDrivers": "",
    "driverVersion": "3.0 Mesa 12.0.3",
    "driverDate": "",
    "webglRenderer": "nouveau -- Gallium 0.4 on NVD9",
    "webgl2Renderer": "(no info)",
    "info": {
      "AzureCanvasBackend": "skia",
      "AzureCanvasAccelerated": 0,
      "AzureFallbackCanvasBackend": "none",
      "AzureContentBackend": "cairo",
      "CairoUseXRender": 0
    },
    "featureLog": {
      "features": [
        {
          "name": "HW_COMPOSITING",
          "description": "Compositing",
          "status": "blocked",
          "log": [
            {
              "type": "default",
              "status": "blocked",
              "message": "Acceleration blocked by platform"
            }
          ]
        },
        {
          "name": "OPENGL_COMPOSITING",
          "description": "OpenGL Compositing",
          "status": "unavailable",
          "log": [
            {
              "type": "default",
              "status": "unavailable",
              "message": "Hardware compositing is disabled"
            }
          ]
        }
      ],
      "fallbacks": []
    },
    "crashGuards": []
  }
}
```

**Comment by ericawright** [comment] 2017-05-16 20:11
Many things re: drag have changed since this issue, closing. Please re-open if it is still bothering you.

**Closed by ericawright** 2017-05-16 20:11 UTC
