### ISSUE TITLE
Pinned tab scroll out of view

### ISSUE THREAD

**Issue by louisremi** [bwinton/TabCenter#1100] opened 2017-06-02 15:51 UTC
I gave Tab Center a try but decided to stick with horizontal tabs.
Recently, I realized my pinned tabs scrolled out of view when I had too many tabs open.
It seems Tab Center is the culprit, and I had to disable the experiment from test pilot to fix this.

See related bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1359120

**Comment by SoftVision-CiprianMuresan** [comment] 2017-06-07 15:23
Hi @louisremi, thanks for the report. However, this is a dupe of #112.

**Closed by SoftVision-CiprianMuresan** 2017-06-07 15:23 UTC

**Comment by louisremi** [comment] 2017-06-07 15:29
Hi, thank you guys for your work on Tab Center.

I want to be sure you understand the seriousness of the issue here. It's not just a feature request: pinned tabs are broken for anyone who decides at some point to give Tab Center a try. We understand that those experiments are just experiments and might not be feature complete or bug free. But breaking current features of the browser is another kind of inconvenience that deserves all your attention I believe.

**Comment by bwinton** [comment] 2017-06-07 15:34
I disagree, and as the person who decides this kind of thing, I'm afraid you're stuck with my decision.  If you want to submit a patch that fixes it, we would be more than happy to spend the time to help you get it merged, but in terms of what we should be working on, this is not as important as the other things we're doing.

Thanks for your input!
