### ISSUE TITLE
Switching between compact dark and default/compact light does not change icons color when Tab Center is enabled

### ISSUE THREAD

**Issue by MikkCZ** [bwinton/TabCenter#1087] opened 2017-05-23 05:36 UTC
Tab Center block icon colors change when in sidebar mode (both fixed and flexible size). When I switch from compact dark theme to compact light (or default theme), all the icons on the toolbar stay in white and are barely visible, until the Firefox restart. Similar when I switch from light (or default) to dark. Originally reported as [bug 1366455](https://bugzilla.mozilla.org/show_bug.cgi?id=1366455).

Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0 ID:20170519133342 CSet: 8e98dab5054dd093a37ba20c62cf0523e484cfbd

![snimek obrazovky porizeny 2017-05-20 09-17-49](https://cloud.githubusercontent.com/assets/3941344/26339738/5eebcf74-3f8a-11e7-914d-714d19cb9604.png)

**Comment by SoftVision-CiprianMuresan** [comment] 2017-05-23 09:50
Hi @MikkCZ, thanks for the report.
I can reproduce this in Windows too using the latest Nightly. The issue is **not** reproducible on the latest Aurora build so I've searched for a regression window.

Last good revision: 6acd711190fced8731a2aa1a1e699cae2b3331ae
First bad revision: c8c1952346f3861dfed9b834db359f5a6a83e475
Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=6acd711190fced8731a2aa1a1e699cae2b3331ae&tochange=c8c1952346f3861dfed9b834db359f5a6a83e475

Looks like the following bug has the changes which introduced the regression:
https://bugzilla.mozilla.org/show_bug.cgi?id=1334642

As of the 12th of June this issue will be reproducible on Dev and Beta versions too. @ericawright, is this a concern? Because Beta and Dev users who have the add-on installed will still have it after they update to v55.

**Comment by ericawright** [comment] 2017-05-23 14:43
@SoftVision-CiprianMuresan 
We are limiting the version to a max of v54, so once June 12 comes and the version on beta changes to v55 then tab center will not be available on beta. We can close this as wontfix.

**Closed by ericawright** 2017-05-23 14:43 UTC

**Comment by SoftVision-CiprianMuresan** [comment] 2017-05-23 15:07
@ericawright, I agree that new users will not be able to install it. But the people who already have it installed, will still have it after they update to v55, I think. If this happens, then all the Nightly issues will also be present.

I've also verified that if you have Tab Center installed on Nightly 54, the add-on is still available after I updated to Nightly 55. 

Could you please explain how the restriction works and if the above scenario would be possible?

**Comment by ericawright** [comment] 2017-05-23 15:18
The desired behavior is that it will be disabled, and will not be able to install on anything greater than v54. The update as well should ideally result in tab center being disabled. We are still working to actually make this happen though.

**Comment by SoftVision-CiprianMuresan** [comment] 2017-05-23 15:22
That explains a lot of things. 😆
