### ISSUE TITLE
Mozilla Firefox Tab Center ISSUE

### ISSUE THREAD

**Issue by eliel-raphael** [bwinton/TabCenter#723] opened 2016-10-24 09:31 UTC
Whenever I enable Tab Center and try to right-click on my Bookmark Toolbar items, the right-click menu is grey and doesn't allow me to click anything.

<img width="1280" alt="screen shot 2016-10-24 at 5 30 36 pm" src="https://cloud.githubusercontent.com/assets/23028085/19640506/9d28510c-9a0f-11e6-82b8-7e6ac1caa8ee.png">

**Comment by eliel-raphael** [comment] 2016-10-24 09:32
Please help me!!!

**Comment by SoftVision-CiprianMuresan** [comment] 2016-10-24 11:02
@eliel-raphael, thank you for reporting this, however it is a duplicate of #583.
A workaround for this issue is to create a custom .xpi, explained [here](https://github.com/bwinton/TabCenter/issues/583#issuecomment-250363560).
A different one would be to open a New Window, where the Bookmark toolbar Context Menu works as expected.

**Closed by SoftVision-CiprianMuresan** 2016-10-24 11:02 UTC

**Comment by eliel-raphael** [comment] 2016-10-25 18:25
Ok, thank you. I changed my mind and left Firefox because Safari was faster. Thanks for letting me know though.
