### ISSUE TITLE
ctrl + click should respect "New tabs are opened at the top"

### ISSUE THREAD

**Issue by mathroc** [bwinton/TabCenter#536] opened 2016-08-17 09:17 UTC
it seems odd that new tab (ctrl+t) are opened at the top when the option is enabled but ctrl+click new tabs are opened below the current tab instead of on just on top of it

it would help keeping recent tab in the same place

**Comment by bwinton** [comment] 2016-08-17 12:36
Yeah, I think this is related to #410 and #491…  Mostly I think we need to do a little more thinking about where things open when the option is enabled and disabled.

(Resolving dupe of #410, where we'll do that thinking.)

Thanks!  🙂

**Closed by bwinton** 2016-08-17 12:36 UTC
