### ISSUE TITLE
Disable vertical scaling

### ISSUE THREAD

**Issue by tostrio** [bwinton/TabCenter#1106] opened 2017-06-14 12:53 UTC
The tab bar auto scales vertically depending on window size and number of tabs. While this might be desirable for some interfaces, it is very confusing for me. It changes the text length (actually the more spacious display shows much less text, which is the most important part of the information) and makes everything jump around, take additional resources for rendering the thumbnail etc.

Is there some way to disable this feature? Would an option to configure it be something that you consider? (Maybe allow user to force one or the other?)

**Comment by SoftVision-CiprianMuresan** [comment] 2017-06-14 12:57
Hi @tostrio, thanks for the report. However this is a dupe of #439. 
You can change the "extensions.verticaltabs.largetabs" pref in about config to "0" to force the tabs to be small all the time.

**Closed by SoftVision-CiprianMuresan** 2017-06-14 12:57 UTC

**Comment by tostrio** [comment] 2017-06-14 13:31
@SoftVision-CiprianMuresan thank you for the info, that solves it completely for me!
