### ISSUE TITLE
Tool tip for sidebarOpen/Shrink is not appropriate

### ISSUE THREAD

**Issue by kshetra03** [bwinton/TabCenter#912] opened 2017-01-31 09:18 UTC
OS: Windows 7 Enterprise SP1. 
Firefox Version: 51.0.1 

Steps to re-create: 
- Click the sidebarOpen/Shrink once(change the previous state). 
- Hover the mouse over the sidebarOpen/Shrink button. The tool tip for the same will show
${strings.sidebarShrink} -- if the sidebar is open
${strings.sidebarOpen} -- if the sidebar is Shrink
- This is showing some part of the code as a tool tip which is not desirable.

**Comment by SoftVision-CiprianMuresan** [comment] 2017-01-31 09:31
Hi @kshetra03, thanks for reporting this, however it is a duplicate of #866.

**Closed by SoftVision-CiprianMuresan** 2017-01-31 09:31 UTC
