### ISSUE TITLE
Allow tab center to always stay in compact mode

### ISSUE THREAD

**Issue by tkafka** [bwinton/TabCenter#634] opened 2016-09-27 11:18 UTC
I find the constant switching between normal and compact mode jarring, as my usual tab set is around the magic number when it toggles - and I much prefer the compact layout as it is cognitively simpler (has all the important info without being visually heavy - tab previews, shadows, borders, 2 lines of text ...).

Could there be an option to always keep the tab center in compact mode?

Compact:
![screenshot 2016-09-27 13 17 43](https://cloud.githubusercontent.com/assets/876717/18871240/cf5260b6-84b4-11e6-9c9a-8c451a1f8912.png)

Normal:
![screenshot 2016-09-27 13 19 51](https://cloud.githubusercontent.com/assets/876717/18871310/24f4ecf0-84b5-11e6-997f-f12d0a1131db.png)

**Comment by bwinton** [comment] 2016-09-27 13:48
Duplicate of #439, which was fixed a while ago.  Thanks for the report!

**Closed by bwinton** 2016-09-27 13:48 UTC

**Comment by tkafka** [comment] 2017-03-02 13:39
Thanks! Awesome!
