### ISSUE TITLE
When typing Vertical Tabs overlap the URL being typed.

### ISSUE THREAD

**Issue by AlexisLust** [bwinton/TabCenter#358] opened 2016-06-10 23:20 UTC
Title + 
Only happens if mouse is extending the tabs when they are not pinned.

**Comment by Keith94** [comment] 2016-08-03 10:34
Duplicate of #89.

**Comment by bwinton** [comment] 2016-08-03 15:09
Yeah, resolved, dupe.  Thanks for the report!

**Closed by bwinton** 2016-08-03 15:09 UTC
