### ISSUE TITLE
New Tab Button has artifacts

### ISSUE THREAD

**Issue by Quicksaver** [bwinton/TabCenter#789] opened 2016-11-16 10:29 UTC
In Nightly, every time I enable Tab Center (click the move tabs to top button then back to side), the new tab button re-creates its ```#newtab-button``` (the new containers menu that appears when you long click the button on Nightly).
<img width="210" alt="firefox_2016-11-16_10-28-45" src="https://cloud.githubusercontent.com/assets/802086/20343749/8f6deb82-abe7-11e6-8c5b-b641665b1792.png">
<img width="209" alt="firefox_2016-11-16_10-29-07" src="https://cloud.githubusercontent.com/assets/802086/20343750/9008a73a-abe7-11e6-8688-9d81e67e96eb.png">

**Comment by SoftVision-CiprianMuresan** [comment] 2016-11-16 11:33
Hi @Quicksaver, thank you for reporting this, however it is a dupe of #600.

**Closed by SoftVision-CiprianMuresan** 2016-11-16 11:33 UTC

**Comment by Quicksaver** [comment] 2016-11-16 11:36
Ah sorry, I looked to see if it was already reported but must have missed it. :)
