### ISSUE TITLE
Does not play well with Firefox Dev Edition Theme

### ISSUE THREAD

**Issue by xbouroseu** [bwinton/TabCenter#574] opened 2016-08-24 15:11 UTC
After i enable Tab Center the FF Dev theme no longer appears as it is supposed to. 

Apart from the FF Dev edition i'm using the "Dev-Edition Theme Enabler" addon for FF release along with a custom stylesheet so i get the same look and feel. So i was able to test it and i saw that the "--chrome-background-color" gets confused with the "--chrome-secondary-background-color".

Here it is with Tab-Center disabled:
![screenshot_18 06 26_24-08-2016](https://cloud.githubusercontent.com/assets/1462165/17935997/01f5c4d0-6a26-11e6-9785-efc2d81d8b3b.png)

Here it is with Tab-Center enabled:
![screenshot_18 07 12_24-08-2016](https://cloud.githubusercontent.com/assets/1462165/17936017/0fedaefe-6a26-11e6-8989-14a29a5ec4c4.png)

**Comment by ericawright** [comment] 2016-08-24 16:30
thank you, I believe this is a duplicate of #566.

**Closed by ericawright** 2016-08-24 16:30 UTC
