### ISSUE TITLE
Race condition when starting up and opening new windows makes new window break

### ISSUE THREAD

**Issue by callahad** [bwinton/TabCenter#675] opened 2016-10-05 15:02 UTC
1. Launch Firefox
2. When the new window appears, but has not yet finished initializing Tab Center, press Cmd-N

What happens:

1. The new window opens, and looks broken.
2. The first window finishes loading as normal.

<img width="1792" alt="screen shot 2016-10-05 at 09 30 14" src="https://cloud.githubusercontent.com/assets/24193/19118666/be68fc0e-8ae2-11e6-8e10-46c36384b64a.png">

**Comment by callahad** [comment] 2016-10-05 15:03
I've tested and can reproduce this on OS X and on Linux. Tiny screencast at http://people.mozilla.org/~dcallahan/tmp/tabcenter.mp4

**Comment by ericawright** [comment] 2016-10-06 17:08
Thank you! I've been able to reproduce, but only on nightly (though it is possible I haven't gotten the timing correct)

**Comment by SoftVision-PaulOiegas** [comment] 2016-10-18 09:30
@ericawright @bwinton  Another user reported on Test Pilot repo this issue with Tab Center and Private Window where the page doesn't loads. Also, we managed to reproduce this on all channels.
I know that, for the moment at least, Tab Center is not working on Private window. But is there a way to correct this so the users could at least use the private window even if they have Tab Center installed ?

**Comment by ericawright** [comment] 2016-10-21 14:36
@callahad after some major changes in the unload function due to #701 I'm not able to reproduce this anymore. Since your machine was able to reproduce so faithfully could you give it a shot again using this XPI?

https://www.dropbox.com/s/ne5i2wu62a0j4hn/tabcentertest1%40mozilla.com-1.26.0.xpi?dl=0

When I get the timing right I seem to get a window without Tab Center but, not broken:

<img width="853" alt="screen shot 2016-10-21 at 10 33 15 am" src="https://cloud.githubusercontent.com/assets/10803178/19602090/e25e2730-9779-11e6-81c3-6dac99f78181.png">

**Comment by callahad** [comment] 2016-10-22 22:24
With that .xpi, I can't reproduce the bug. Bravo!

**Comment by ericawright** [comment] 2016-10-24 15:33
fixed by  #701

**Closed by ericawright** 2016-10-24 15:33 UTC
