### ISSUE TITLE
Active tab changes while just scrolling

### ISSUE THREAD

**Issue by abdulmoeedammar** [bwinton/TabCenter#171] opened 2016-05-11 13:54 UTC
I am facing some weird behavior, when I hover my mouse pointer to Tab Center and scroll using two finger scroll, sometimes tabs start switching. I have a lot tabs open, and it seems like when scrolling reaches very top or bottom, further scrolling starts changing active tab.

I am using firefox on Fedora 23 on Thinkpad T530.

**Comment by johngruen** [comment] 2016-05-11 20:41
@ericawright can you repro

**Comment by wresuolc** [comment] 2016-05-16 18:07
We couldn't reproduce this.

**Comment by abdulmoeedammar** [comment] 2016-05-18 14:32
I am sorry to hear that, on my side it happens quite easily and frequently.

Here is the video showing what happens: 
https://www.dropbox.com/s/65indehuda1wtxm/tabcenter.mkv?dl=0

**Comment by glasserc** [comment] 2016-06-03 14:23
I also see this behavior, but on further exploration, it seems that what's happening is that when I scroll left or right, it switches tabs very rapidly. I think what's happening is that my vertical scrolling isn't perfectly vertical, so the horizontal motion is turned into a switch-tab action.

**Comment by bwinton** [comment] 2016-06-03 14:44
Wait, is horizontal scrolling to switch tabs a default behaviour, or is that provided by an add-on?

**Comment by glasserc** [comment] 2016-06-03 15:02
I think it's provided by Tab Center. When I disable Tab Center, scrolling vertically or horizontally while over the tab bar just scrolls the tab bar.

**Comment by chris-morgan** [comment] 2016-07-02 00:50
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1192327, of which there is a suggestion that it may be fixed in what I think will be Firefox 49. I’m using Nightly at present with this extension (rather than Tree Style Tab on stable as I have on another device) and I’m not observing the described behaviour.

**Closed** 2017-04-27 15:30 UTC
Labels: bug, p3, ready
