### ISSUE TITLE
Possible to hide the sidebar so you can't close tabs

### ISSUE THREAD

**Issue by ekr** [bwinton/TabCenter#1063] opened 2017-04-21 23:43 UTC
If you minimize the sidebar enough, so that it just shows the favicon, then there's no room for the tab-closing X, even if you hover

**Comment by SoftVision-PaulOiegas** [comment] 2017-04-24 08:39
Hi @ekr and thanks for reporting this ! However it is a dupe of #836, so I am closing it in favor of that one. Please direct any questions or details there.

Until a decision will be taken in this case, as a workaround, you should either use the auto-hide option. Or, you can use the next 2 ways to manually close tabs:
1. You can use the mouse wheel click. This closes the tab the mouse pointer is hovering on.
2. Ctrl+w (Windows) or Cmd+w (Mac OS) is a keyboard shortcut for closing the focused tab.

**Closed by SoftVision-PaulOiegas** 2017-04-24 08:39 UTC
