### ISSUE TITLE
Needs an option to show small tabs always

### ISSUE THREAD

**Issue by Temeez** [bwinton/TabCenter#700] opened 2016-10-14 07:42 UTC
[I don't like needing] to have an x amount of tabs open before the tabs get smaller. I don't have time to look at the thumbnail, url and then the title to find the tab that I'm looking for!

**Comment by andrewshadura** [comment] 2016-10-14 13:59
👍

**Comment by bwinton** [comment] 2016-10-14 14:00
(Edited to remove insults.)

**Comment by bwinton** [comment] 2016-10-14 14:03
Also, this is a duplicate of issue #439.  Thanks for the report, though!

**Closed by bwinton** 2016-10-14 14:03 UTC
