### ISSUE TITLE
Zombie tabs

### ISSUE THREAD

**Issue by hwine** [bwinton/TabCenter#1091] opened 2017-05-26 00:31 UTC
I just got a zombie tab:

![image](https://cloud.githubusercontent.com/assets/132412/26475726/54d0ca4a-416e-11e7-9b73-7173cc90e1b8.png)

That tab happened to be a jupyter notebook with unsaved changes, so the "stay/leave page?" dialog was up. I closed via cmd-W. I haven't been able to recreate with several attempts. But neither will the tab go away.

The hover continues to show the original tab's title, but clicking in the zombie tab actually displays the 2nd (1st live) tab.

I am using containers, but the zombie tab was not a container.
With 55.0a1 (2017-05-25) (64-bit) on macOS 10.12.5

**Comment by SoftVision-CiprianMuresan** [comment] 2017-05-26 08:05
Hi @hwine, thanks for the report. However, this issue is a dupe of #1077 and was already fixed in the latest master.
A new release is planned to land in the following days.

Also, Tab Center will no longer be be compatible with v55 starting with the next release.

**Closed by SoftVision-CiprianMuresan** 2017-05-26 08:05 UTC
