### ISSUE TITLE
External links go to the bottom of the tab list, not the top

### ISSUE THREAD

**Issue by kumar303** [bwinton/TabCenter#491] opened 2016-08-05 19:21 UTC
When you open a URL in Firefox after clicking a link from an external application (such as an IRC client), the tab is added to the bottom of the tab list. If you click the 'New Tab' button from within Firefox, the tab is created at the top of the list. 

This is inconsistent and makes it hard to keep track of recently visited tabs. 

I personally like adding new tabs to the top of the list because there is less chance that it will get buried at the bottom of the screen.

**Comment by ncalexan** [comment] 2016-08-08 20:34
This and #493 are duplicates.  I  think the description in #493 is slightly better, tbh, but this one was filed earlier.

In any case, I'd like to see the suggested change implemented!

**Comment by bwinton** [comment] 2016-08-17 12:37
I'm actually going to resolve this as a dupe of #410, where we should do some thinking about where things open with various options enabled.

**Closed by bwinton** 2016-08-17 12:37 UTC
