### ISSUE TITLE
Auto-expanded tabs cover the left side of the bookmarks toolbar, impeding drag-and-drop creation of bookmarks

### ISSUE THREAD

**Issue by terrycloth** [bwinton/TabCenter#707] opened 2016-10-17 02:59 UTC
Creating bookmarks by performing drag-and-drop on a tab makes things easier particularly when you want the bookmark to go in a certain folder. However, when auto-expanded, Tabs Center covers the leftmost folders in the bookmarks toolbar, so you may not be able to place the bookmark in its final destination in one motion.

![screenshot from 2016-10-16 19-45-23](https://cloud.githubusercontent.com/assets/3881885/19423853/376b6e44-93d9-11e6-9c39-af9ed9b4873a.png)

There are a few workarounds which make this a less urgent issue, but which are still less than ideal:

1. Drag the tab further to the right in the bookmark toolbar, let Tabs Center collapse again, then drag the bookmark again to its destination folder.
2. Lock the tabs side bar open before dragging and dropping the tab.
3. Use the bookmarks menu "star" button (or keyboard shortcut) to bookmark the current page, then expand the Folders sub-menu, and search for and select the folder you want.

The proper solution, I think, would probably be to let the tabs side bar collapse again *during* the drag-and-drop motion, just as the mouse leaves the expanded tabs area.

****

I play around with Firefox stable, Firefox beta, and Firefox Developer Edition on Fedora 24 with GNOME Shell. Lately, though, I've been using Firefox beta the most (currently version 50.0b7).

**Comment by ericawright** [comment] 2016-10-19 17:47
thank you, this is a dupe of #673

**Closed by ericawright** 2016-10-19 17:47 UTC
